### PR TITLE
Add sentiment analysis and automerge for dependabot

### PR DESCRIPTION
**Pull request by HashTalmiz**
This PR is for: https://github.com/asyncapi/asyncapi/issues/445

**Description**
_GH Actions PR_
- Added Sentiment Analysis workflow
- `pull_request` changed to `pull_request_target` in `.github/workflows/welcome-first-time-contrib.yml` file
- Added Automerge workflow

Resolves: #445
NPM run test works 100%

### CODE REVIEW

**Comment by HashTalmiz** [comment]
Seems like #445 is a duplicate to the same issue.

**Comment by derberg** [comment]
@HashTalmiz https://github.com/asyncapi/asyncapi/issues/445 is for this `asyncapi` repo while https://github.com/asyncapi/.github/issues/9 for `.github` repo. GitHub Actions unfortunately do not yet support global actions, this is why we need to duplicate many workflows across all repos 😞 thus every repo has its own issue. I will adjust description of this PR so after merge proper issue is closed

**Comment by derberg** [comment]
@HashTalmiz great stuff man, merged. I just changed description of PR a bit to make it more ❤️ and follow imperative mode. It is important

**Comment by HashTalmiz** [comment]
They looked very similar hence I misunderstood it as a duplicate :sweat_smile:

**Pull request merged**
