### PR TITLE
Removed try-catch in test's index.js

### LINKED ISSUE #440: Remove not needed try/catch from the test
*Context*

SonarCloud says that [this](https://github.com/asyncapi/asyncapi/blob/master/test/index.js#L15-L39) try/catch is a code smell because we are anyway not doing anything special in the `catch` clause. 

*Description*

Instead of adding there `console.error` it is better to remove the try/catch statement as the error will bubble up anyway to the `runForVersion` function where error is handled much better.﻿

### PR DESCRIPTION
**Pull request by HashTalmiz**
**Description**
- Just had to remove the _smelly code_ by getting rid of the try catch block. Tests run perfectly showing that the future is bright! :100: 

**Related issue(s)**
Fixes #440

### CODE REVIEW

**Review by derberg — APPROVED** [review]
Oh boy, you were to fast, Hacktoberfest did not start yet 😄 
Thanks a lot for the PR!

**Comment by HashTalmiz** [comment]
Haha, Glad to help!

**Comment by derberg** [comment]
It is actually not included in the release. This was an unintentional release caused by the release automation initial run. 1.0 version of the spec was released a long time ago. The release mentioned by the bot was removed.

**Comment by derberg** [comment]
Not included in release 2.1 yet, 2.1 was mistakenly triggered by our automation.

**Pull request merged**
